// Runs bench.mjs and writes a Markdown and JSON report.
//
//   node report.mjs [--markdown path] [--json path] [--title text]
//
// Without options, it writes ../docs/benchmarks.md and ../docs/benchmarks.json.

import { execFileSync } from "node:child_process";
import {
	readFileSync,
	writeFileSync,
} from "node:fs";
import { cpus } from "node:os";
import { parseArgs } from "node:util";

const { values: options } = parseArgs({
	options: {
		markdown: { type: "string" },
		json: { type: "string" },
		title: { type: "string", default: "Benchmarks" },
	},
});

if (!options.markdown && !options.json) {
	options.markdown = "../docs/benchmarks.md";
	options.json = "../docs/benchmarks.json";
}

const exec = (command, args, env) =>
	execFileSync(command, args, {
		cwd: import.meta.dirname,
		env: { ...process.env, ...env },
		encoding: "utf8",
		maxBuffer: 1 << 30,
		stdio: ["ignore", "pipe", "inherit"],
	});

exec("npm", ["--prefix", "..", "run", "build"]);
const output = JSON.parse(exec(process.execPath, ["bench.mjs"], { BENCHMARK_RUNNER: "1" }));

// Each mitata group has lzma1 and the baseline.
const benchmarks = new Map();
for (const { group, baseline, runs } of output.benchmarks) {
	const name = output.layout[group].name;
	const entry = benchmarks.get(name) ?? { name };
	entry[baseline ? "baseline" : "lzma1"] = Math.round(runs[0].stats.avg);
	benchmarks.set(name, entry);
}

const report = {
	version: JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8")).version,
	commit: exec("git", ["describe", "--always", "--dirty", "--exclude=*"]).trim(),
	baseline: output.benchmarks.find((b) => b.baseline).alias,
	runtime: `Node.js ${process.versions.node}`,
	cpu: cpus()[0].model,
	date: new Date().toISOString().slice(0, 10),
	/** Average time per call in nanoseconds. */
	benchmarks: [...benchmarks.values()],
};

if (options.json) writeFileSync(options.json, JSON.stringify(report, null, "\t") + "\n");
if (options.markdown) writeFileSync(options.markdown, markdown(report));

function markdown(r) {
	return [
		`# ${options.title}`,
		"",
		`- **lzma1 (latest):** ${r.version}, commit ${r.commit}`,
		`- **Baseline:** ${r.baseline}`,
		`- **Runtime:** ${r.runtime}`,
		`- **CPU:** ${r.cpu}`,
		`- **Date:** ${r.date}`,
		"",
		"Times are averages per call, measured with [mitata](https://github.com/evanwashere/mitata).",
		"Both versions run in the same process, so the speedup is comparable between",
		"machines, the times are not. Generated by `bench/report.mjs`.",
		"",
		`| Benchmark | ${r.baseline} | lzma1 (latest) | Speedup |`,
		"| --- | --: | --: | --: |",
		...r.benchmarks.map((b) => `| ${b.name} | ${time(b.baseline)} | ${time(b.lzma1)} | ${(b.baseline / b.lzma1).toFixed(2)}× |`),
		"",
	].join("\n");
}

function time(ns) {
	if (ns < 1e3) return `${ns} ns`;
	if (ns < 1e6) return `${(ns / 1e3).toFixed(2)} µs`;
	if (ns < 1e9) return `${(ns / 1e6).toFixed(2)} ms`;
	return `${(ns / 1e9).toFixed(2)} s`;
}
