name: quality checks

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
        paths:
            - src/**.ts
            - package.json
            - tsconfig.json
            - .github/workflows/**.yml

permissions:
    contents: read
    pull-requests: write
    actions: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: oven-sh/setup-bun@v2

            - name: install
              run: bun install

            - name: typecheck
              run: bun run typecheck

            - name: test
              run: bun run test

            - name: upload coverage artifact
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: coverage/lcov.info
                  if-no-files-found: warn

    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: |
                  bun install
                  bun fmt:check
