name: release-please

on:
    push:
        branches:
            - master
            - next
    workflow_run:
        workflows:
            - "quality checks"
        types:
            - completed
    workflow_dispatch:
        inputs:
            tag:
                description: Tag to release manually
                required: false
                type: string

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        if: github.ref_name == 'master'
        steps:
            - uses: googleapis/release-please-action@v4
              if: ${{ !github.event.inputs.tag }}
              id: release
              with:
                  manifest-file: .github/.release-please-manifest.json
                  config-file: .github/.release-please-config.json
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  target-branch: ${{ github.ref_name }}

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              with:
                  ref: ${{ github.event.inputs.tag || github.ref_name }}

            - uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag}}
              with:
                  node-version-file: ".nvmrc"
                  registry-url: "https://registry.npmjs.org"

            - if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: >
                  npm install &&
                  npm run build &&
                  npm publish --provenance --access public --tag latest

    prerelease:
        runs-on: ubuntu-latest
        if: ${{ github.ref_name == 'next' }}
        steps:
            - uses: googleapis/release-please-action@v4
              if: ${{ !github.event.inputs.tag }}
              id: prerelease
              with:
                  manifest-file: .github/.release-please-manifest.json
                  config-file: .github/.pre-release-please-config.json
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  target-branch: ${{ github.ref_name }}

            - uses: actions/checkout@v4
              if: ${{ steps.prerelease.outputs.release_created || github.event.inputs.tag }}
              with:
                  ref: ${{ github.event.inputs.tag || github.ref_name }}

            - uses: actions/setup-node@v4
              if: ${{ steps.prerelease.outputs.release_created || github.event.inputs.tag}}
              with:
                  node-version-file: ".nvmrc"
                  registry-url: "https://registry.npmjs.org"

            - if: ${{ steps.prerelease.outputs.release_created || github.event.inputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: >
                  npm install &&
                  npm run build &&
                  npm publish --provenance --access public --tag next
